In [7]:
import pandas as pd

var1 = pd.DataFrame({"A":[1,2,3,4],"B":[11,22,33,44]},index=["a","b","c","d"])
var2 = pd.DataFrame({"C":[10,40],"D":[43,54]},index=["a","b"]) #index is alway equal to the given value
var2.join(var1,how="right") #we can inter change the var1<-->var2
#how =(left,right,outer-->{union ka kaam krta h},inner-->{inter section data})

      C     D  A   B
a  10.0  43.0  1  11
b  40.0  54.0  2  22
c   NaN   NaN  3  33
d   NaN   NaN  4  44

In [8]:
var1 = pd.DataFrame({"A":[1,2,3,4],"B":[11,22,33,44]},index=["a","b","c","d"])
var2 = pd.DataFrame({"A":[10,40],"B":[43,54]},index=["a","b"]) #index is alway equal to the given value
var2.join(var1,how="inner",lsuffix="_12")
#lsuffix-->left suffix/rsuffix-->right suffix

   A_12  B_12  A   B
a    10    43  1  11
b    40    54  2  22

APPEND-->

difference in the joint and append function-->?
--> in join columns value is same they throught error and we use SUFFIX in ppend we dont need

In [11]:
var1 = pd.DataFrame({"A":[1,2,3,4],"B":[11,22,33,44]})
var2 = pd.DataFrame({"C":[10,40,50,60],"D":[43,54,74,67]})

var1.join(var2,ignore_index=True)

TypeError: DataFrame.join() got an unexpected keyword argument 'ignore_index'