In [20]:
import pandas as pd

In [21]:
df = pd.read_csv("Test_new3.csv")
df

              Name    Nationality     Sex  Age Handedness
0         John Doe       American    Male   34      Right
1       Jane Smith        British  Female   28       Left
2  Michael Johnson       Canadian    Male   45      Right
3      Emily Davis     Australian  Female   22      Right
4      David Brown          Irish    Male   36       Left
5      Linda White  South African  Female   31      Right

Crosstab function --> also known as the contingency table and cross tabulation
--> it a type of table in a matrix format that is used for count thefrequency of the variable & the element

-->crosstab method is only on the pandas and not on the dataframes

In [29]:
pd.crosstab([df.Sex,df.Handedness],[df.Nationality],margins=True) #margins is used for getting total no. od handedness

Nationality        American  Australian  British  Canadian  Irish  \
Sex    Handedness
Female Left               0           0        1         0      0
       Right              0           1        0         0      0
Male   Left               0           0        0         0      1
       Right              1           0        0         1      0
All                       1           1        1         1      1

Nationality        South African  All
Sex    Handedness
Female Left                    0    1
       Right                   1    2
Male   Left                    0    1
       Right                   0    2
All                            1    6

In [28]:
pd.crosstab([df.Sex],[df.Handedness],normalize='index') #normalize is giving na percentage

Handedness      Left     Right
Sex
Female      0.333333  0.666667
Male        0.333333  0.666667

In [30]:
import numpy as np
pd.crosstab([df.Sex],[df.Handedness],values=df.Age,aggfunc=np.average)

Handedness  Left  Right
Sex
Female      28.0   26.5
Male        36.0   39.5